language: java

jdk:
- openjdk6

env:
- TERM=dumb

before_install:
- chmod +x gradlew

script: ./gradlew -PbuildNumber=${TRAVIS_BUILD_NUMBER} -PrevisionNumber=${TRAVIS_COMMIT} -PbranchName=${TRAVIS_BRANCH} clean test check dist integration

after_success:
- gradle cobertura
- gradle coveralls
